---
title: "Host filtering"
author: "James Abbott"
date: "04/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(DESeq2)
library(tidyverse)
library(data.table)
library(ggplot2)
library(ggthemes)
library(cowplot)
library(phyloseq)

knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "/cluster/db/jabbott/host_filtering/")
```

```{r dataprep}
get_counts<-function(headname) {
  name_parts<-(strsplit(headname,'\\.'))[[1]]
  
  if (name_parts[[1]]=='pre') {
    dir='nt_unfiltered'
  } else {
    dir='nt_morex3'
  }
  
  path=file.path('kraken',dir,paste0(name_parts[[2]],'.report.txt'))
  
  df<-read.csv(path,sep="\t",col.names=c('prop',headname,'count','rank','taxid','taxa')) %>% 
    filter(rank=='G') %>%
    select(taxa,taxid,all_of(headname))
  
  df$taxa<-trimws(df$taxa,which='left')
    
  return(df)
}

# just interested in bulk and elite here, but will pick them pre and post filtering
bulk_samples=c('pre.2000','pre.2001','pre.2002','post.2000','post.2001','post.2002')
elite_samples=c('pre.2023','pre.2024','pre.2025','post.2023','post.2024','post.2025')

bulk_df<-lapply(bulk_samples, get_counts) %>%
  reduce(left_join,by='taxa') %>%
  replace(is.na(.),0) %>%
  column_to_rownames('taxa') %>%
  select(taxid.x,unlist(bulk_samples))

elite_df<-lapply(elite_samples,get_counts) %>%
  reduce(left_join,by='taxa') %>%
  replace(is.na(.),0) %>%
  column_to_rownames('taxa') %>%
  select(taxid.x,unlist(elite_samples))
```

```{r}
bulk_counts<-bulk_df %>% 
  select(-taxid.x) %>% 
  as.matrix()
condition=factor(c(rep('pre',3),c(rep('post',3))))
coldata<-data.frame(row.names=colnames(bulk_counts),condition)

dds<-DESeqDataSetFromMatrix(countData=bulk_counts,colData=coldata,design= ~ condition)
keep <- rowSums(counts(dds)) >= 50
dds <- dds[keep,]
dds<-DESeq(dds)
rld <- rlogTransformation(dds)
res<-results(dds,alpha=0.05, contrast=c("condition",'pre','post'))
summary(res)

bulk_df<-rownames_to_column(bulk_df,var='taxa')
bulk_res<-as.data.frame(res)
bulk_res <- bulk_res[order(bulk_res$log2FoldChange), ] %>%
  filter(padj <= 0.05) %>%
  rownames_to_column(var='taxa') %>%
  left_join(bulk_df,by='taxa')

elite_counts<-elite_df %>%
  select(-taxid.x) %>%
  as.matrix()
  
dds<-DESeqDataSetFromMatrix(countData=elite_counts,colData=coldata,design= ~ condition)
dds<-DESeq(dds)

rld <- rlogTransformation(dds)
res<-results(dds,alpha=0.05, contrast=c("condition",'pre','post'))
summary(res)

elite_df<-rownames_to_column(elite_df,var='taxa')
elite_res<-as.data.frame(res)
elite_res <- elite_res[order(elite_res$log2FoldChange), ] %>%
  filter(padj <= 0.05) %>%
  rownames_to_column(var='taxa') %>%
  left_join(elite_df,by='taxa')
```
```{r output}
dir.create('deseq2', showWarnings = FALSE)

bulk_res<-bulk_res %>%
  relocate('taxid.x',.after = 'taxa') %>%
  rename('taxid'='taxid.x')

elite_res<-elite_res %>%
  relocate('taxid.x',.after = 'taxa') %>%
  rename('taxid'='taxid.x')

write.table(bulk_res,file.path('deseq2','bulk.txt'),sep="\t",quote=FALSE,row.names = FALSE)
write.table(elite_res,file.path('deseq2','elite.txt'),sep="\t",quote=FALSE,row.names = FALSE)
```

## Phyloseq analysis of kraken outputs

Phyloseq reports have been converted into a biom file using kraken-biom, which will hopefully load into phyloseq ok...

```{r phyloseq_prep}
samples_df<-read.csv('map.txt',header = TRUE,sep="\t")
row.names(samples_df)<-samples_df$SampleID
samples<-row.names(samples_df)
SAM = sample_data(samples_df, errorIfNULL = T)
ps<-import_biom('kraken/biom/table.biom.gz')
colnames(tax_table(ps))<-c("Kingdom","Phylum","Class","Order","Family","Genus","Species")

bact_ps<-subset_taxa(ps,Kingdom=='k__Bacteria')
bact_ps<-prune_samples(samples,bact_ps)
bact_ps<-phyloseq(otu_table(bact_ps),tax_table(bact_ps),SAM)
```

```{r abundance_plots}
glommed<-tax_glom(bact_ps,taxrank='Phylum')
dat<-data.table(psmelt(glommed))
dat$Phylum<-as.character(dat$Phylum)
dat[, median := median(Abundance, na.rm = TRUE), by = "Phylum"]
# Change name to remainder of Phylum less than arbitrary cutoff to match 1%...
dat[(median <= 40000), Phylum := "Others"]
dat$Filtered=factor(dat$Filtered,levels=c('Unfiltered','Filtered'))
p1 <- ggplot(data=dat, aes(x=Sample, y=Abundance, fill=Phylum)) + geom_bar(aes(), stat="identity", position="stack") +
  theme_bw() + theme(legend.position = "none", axis.text.x=element_blank())+scale_fill_colorblind() +
  xlab('')+ylab('Absolute Abundance')+facet_grid(~ Filtered,scales="free",space="free")


phy<-transform_sample_counts(bact_ps,function(x) x/sum(x))
glommed<-tax_glom(phy,taxrank='Phylum')
dat<-data.table(psmelt(glommed))
dat$Phylum<-as.character(dat$Phylum)
dat[, median := median(Abundance, na.rm = TRUE), 
    by = "Phylum"]
# Change name to remainder of Phylum less than 1%
dat[(median <= 0.01), Phylum := "Others < 1% abundance"]
dat$Filtered=factor(dat$Filtered,levels=c('Unfiltered','Filtered'))

p2 <- ggplot(data=dat, aes(x=Sample, y=Abundance, fill=Phylum)) + geom_bar(aes(), stat="identity", position="stack") +
  theme_bw() + theme(legend.position='bottom',axis.text.x=element_blank() )+ 
  scale_fill_colorblind() + xlab('') + ylab('Relative Abundance')+facet_grid(~ Filtered,scales='free',space='free')
legend<-get_legend(p2)
p2<-p2 + theme(legend.position = 'none')
p<-plot_grid(plot_grid(p1,p2,ncol=2),plot_grid(NULL,legend,ncol=1),nrow=2,rel_heights = c(0.75,0.2),greedy=FALSE,align='hv')
p
```
```{r bray_distance}
distmat<-phyloseq::distance(bact_ps,method='bray')
mds<-ordinate(bact_ps,"MDS",distance=distmat)
dist_plot<-plot_ordination(bact_ps,mds,color = 'Filtered',title = 'Bray PCoA')
dist_plot<-dist_plot+theme_bw()+scale_color_colorblind()
dist_plot
```